---
# tasks file for ec2-iam-users

- name: Enable the epel-relase repo
  yum:
    name: epel-release
    state: present
  ignore_errors: true
  register: epel_repo

- name: Fallback for epel-release on Amazon Linux
  command: amazon-linux-extras install -y epel
  when: epel_repo is failed

- name: Assure essential system packages are installed
  yum:
    name:
      - jq
      - openssh-server
      - python-pip
      - util-linux
    state: present

- name: Assure essential PIP packages are installed
  pip:
    name:
      - awscli

- name: Enable fetching the public keys from IAM
  template:
    src: "fetch-public-keys-from-iam.sh"
    dest: "/usr/bin/fetch-public-keys-from-iam"
    mode: 0755

- name: Authorize SSH via IAM public keys
  template:
    src: "ssh-authorize-via-iam.sh"
    dest: "/usr/bin/ssh-authorize-via-iam"
    mode: 0755

- name: Create the group for the IAM users
  group:
    name: "{{ linux_group }}"
    state: present

- name: Copy the sshd_config file
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0644
  register: sshd_config

- name: Restart the SSH service if needed
  systemd:
    name: sshd
    state: restarted
  when: sshd_config is changed and 'no-systemd' not in group_names
