---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ec2-iam-users-ssh-instance
    groups:
      - ssh
    image: solita/centos-systemd-ssh
    override_command: false
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

    networks:
      - name: ec2-iam-users-network
    published_ports:
      - "32768:22"

  - name: ec2-iam-users-amazon-instance
    image: amazonlinux:2
    networks:
      - name: ec2-iam-users-network
    groups:
      - no-systemd

provisioner:
  name: ansible
  options:
    v: true
  config_options:
    defaults:
      stdout_callback: debug
  lint:
    name: ansible-lint

verifier:
  name: testinfra
  lint:
    name: flake8

scenario:
  name: default
  test_sequence:
    - lint
    - dependency
    # - cleanup  (commented so won't destroy the localstack container)
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
