---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ec2-iam-users-ssh-instance
    groups:
      - ssh
    image: jdeathe/centos-ssh
    networks:
      - name: ec2-iam-users-network
    published_ports:
      - "32768:22"
    env:
      SSH_USER_PASSWORD: "password"
      SSH_PASSWORD_AUTHENTICATION: "true"
      SSH_SUDO: "ALL=(ALL) NOPASSWD:ALL"

  - name: ec2-iam-users-amazon-instance
    image: amazonlinux:2
    networks:
      - name: ec2-iam-users-network

provisioner:
  name: ansible
  options:
    v: true
  lint:
    name: ansible-lint

verifier:
  name: testinfra
  lint:
    name: flake8
